# Generated by Django 3.2.10 on 2022-03-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='color',
            field=models.CharField(blank=True, choices=[('BLUE', 'BLUE'), ('RED', 'RED'), ('GREEN', 'GREEN')], max_length=15),
        ),
    ]
