# Generated by Django 3.2.10 on 2022-03-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_task', '0003_rename_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_number',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
