# Generated by Django 3.2.10 on 2022-04-08 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='files/private_msg/')),
                ('key', models.CharField(max_length=40)),
                ('date_create', models.DateTimeField(default=datetime.datetime.now)),
                ('date_for_del', models.DateTimeField(default=datetime.datetime(2023, 4, 8, 0, 40, 32, 702535))),
            ],
        ),
    ]
