# Generated by Django 3.2.10 on 2022-04-08 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_private_msg', '0002_alter_privatemsg_date_for_del'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemsg',
            name='date_for_del',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 8, 0, 41, 3, 259658)),
        ),
    ]
