# Generated by Django 3.2.10 on 2022-04-09 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_private_msg', '0006_auto_20220408_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemsg',
            name='date_for_del',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 9, 1, 37, 53, 146924)),
        ),
        migrations.AlterField(
            model_name='privatemsg',
            name='msg',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
