# Generated by Django 3.2.10 on 2022-04-13 03:48

import APP_private_msg.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_private_msg', '0007_auto_20220409_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemsg',
            name='voice_msg',
            field=models.FileField(blank=True, upload_to=APP_private_msg.models.format_private_file_upload),
        ),
        migrations.AlterField(
            model_name='privatemsg',
            name='date_for_del',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 3, 48, 37, 320913)),
        ),
    ]
