# Generated by Django 3.2.10 on 2022-04-13 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_private_msg', '0008_auto_20220413_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemsg',
            name='date_for_del',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 13, 7, 7, 38, 290393)),
        ),
    ]
