# Generated by Django 3.2.10 on 2022-01-24 03:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('version', models.CharField(default=None, max_length=30)),
                ('desc', models.TextField(blank=True)),
                ('img_url', models.CharField(blank=True, max_length=200, null=True)),
                ('review_ulr', models.CharField(blank=True, max_length=200, null=True)),
                ('price_week', models.FloatField(blank=True, null=True)),
                ('price_month', models.FloatField(blank=True, null=True)),
                ('price_6_month', models.FloatField(blank=True, null=True)),
                ('price_forever', models.FloatField(blank=True, null=True)),
                ('date_update', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
