# Generated by Django 3.2.10 on 2022-01-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='name_short',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
