# Generated by Django 3.2.10 on 2022-01-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_shop', '0002_products_name_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='img_url',
        ),
    ]
