# Generated by Django 3.2.10 on 2022-01-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_shop', '0003_remove_products_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price_6_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_forever',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
