# Generated by Django 3.2.10 on 2022-01-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_shop', '0004_auto_20220124_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('xLGM_date_end', models.DateTimeField(blank=True, default='')),
                ('xLGM_count', models.IntegerField(default=0)),
                ('xLUMRA_date_end', models.DateTimeField(blank=True, default='')),
                ('xLUMRA_count', models.IntegerField(blank=True, default='')),
            ],
        ),
    ]
