# Generated by Django 3.2.10 on 2022-01-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_shop', '0005_userlicense'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlicense',
            name='xLGM_billid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userlicense',
            name='xLUMRA_billid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
