# Generated by Django 3.2.10 on 2022-01-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_shop', '0006_auto_20220125_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlicense',
            name='pay_link',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
