# Generated by Django 3.2.10 on 2022-01-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_shop', '0007_userlicense_pay_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlicense',
            name='xLGM_date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlicense',
            name='xLUMRA_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userlicense',
            name='xLUMRA_date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
