# Generated by Django 3.2.10 on 2022-01-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_shop', '0008_auto_20220125_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='name_short',
        ),
        migrations.AlterField(
            model_name='userlicense',
            name='xLGM_billid',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
