# Generated by Django 3.2.10 on 2022-01-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_shop', '0010_auto_20220127_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlicense',
            name='pay_link',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='userlicense',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
