# Generated by Django 3.2.10 on 2022-01-27 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_shop', '0011_auto_20220127_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 28, 1, 37, 16, 537415)),
        ),
    ]
