# Generated by Django 3.2.10 on 2022-01-27 22:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('APP_shop', '0013_alter_products_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 27, 22, 43, 59, 860021, tzinfo=utc)),
        ),
    ]
