# Generated by Django 3.2.10 on 2022-01-27 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('APP_shop', '0015_alter_products_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='date_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
