# Generated by Django 3.2.10 on 2022-01-27 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_shop', '0016_alter_products_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='date_update',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
    ]
