# Generated by Django 3.2.10 on 2022-01-27 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_shop', '0018_alter_products_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlicense',
            name='xLGM_date_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='userlicense',
            name='xLUMRA_date_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
