# Generated by Django 3.2.10 on 2022-02-21 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_shop', '0019_auto_20220128_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlicense',
            name='xLCracker_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userlicense',
            name='xLCracker_date_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
