# Generated by Django 3.2.10 on 2022-03-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_shop', '0020_auto_20220221_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='distr',
            field=models.FileField(blank=True, default='', upload_to='files/'),
        ),
    ]
