# Generated by Django 3.2.10 on 2022-03-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_home', '0030_file'),
        ('APP_shop', '0021_products_distr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='distr',
        ),
        migrations.AddField(
            model_name='products',
            name='distrs',
            field=models.ManyToManyField(to='APP_home.File'),
        ),
    ]
