# Generated by Django 3.2.10 on 2022-01-18 20:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_home', '0002_alter_unconfirmeduser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='unconfirmeduser',
            name='date1',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
