# Generated by Django 3.2.10 on 2022-01-18 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_home', '0003_unconfirmeduser_date1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unconfirmeduser',
            name='date1',
        ),
    ]
