# Generated by Django 3.2.10 on 2022-01-20 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_home', '0004_remove_unconfirmeduser_date1'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnconfirmedPasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=200)),
                ('CODE', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
    ]
