# Generated by Django 3.2.10 on 2022-01-27 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_home', '0005_unconfirmedpasswordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unconfirmedpasswordreset',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 28, 1, 37, 16, 536498), null=True),
        ),
        migrations.AlterField(
            model_name='unconfirmeduser',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 28, 1, 37, 16, 535581), null=True),
        ),
    ]
