# Generated by Django 3.2.10 on 2022-01-27 22:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_home', '0006_auto_20220128_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unconfirmedpasswordreset',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 27, 22, 42, 29, 467875), null=True),
        ),
        migrations.AlterField(
            model_name='unconfirmeduser',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 27, 22, 42, 29, 466989), null=True),
        ),
    ]
