# Generated by Django 3.2.10 on 2022-01-27 22:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('APP_home', '0008_auto_20220128_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unconfirmedpasswordreset',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 27, 22, 48, 22, 471788, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='unconfirmeduser',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 27, 22, 48, 22, 470902, tzinfo=utc), null=True),
        ),
    ]
