# Generated by Django 3.2.10 on 2022-01-27 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('APP_home', '0009_auto_20220128_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unconfirmedpasswordreset',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='unconfirmeduser',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
