# Generated by Django 3.2.10 on 2022-01-27 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_home', '0011_auto_20220128_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unconfirmedpasswordreset',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='unconfirmeduser',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
