# Generated by Django 3.2.10 on 2022-01-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_home', '0016_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
