# Generated by Django 3.2.10 on 2022-01-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_home', '0017_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
