# Generated by Django 3.2.10 on 2022-01-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_home', '0018_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='unconfirmeduser',
            name='nickname',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
