# Generated by Django 3.2.10 on 2022-01-29 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_home', '0022_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unconfirmeduser',
            name='nickname',
        ),
    ]
