# Generated by Django 3.2.10 on 2022-01-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_home', '0023_remove_unconfirmeduser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='unconfirmeduser',
            name='gender',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
