# Generated by Django 3.2.10 on 2022-02-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_home', '0024_unconfirmeduser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='HWID',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
    ]
