# Generated by Django 3.2.10 on 2022-02-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_home', '0025_user_hwid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='HWID',
            field=models.CharField(blank=True, default=None, max_length=38, null=True),
        ),
    ]
