# Generated by Django 3.2.10 on 2022-02-26 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP_home', '0027_alter_user_hwid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
