# Generated by Django 3.2.10 on 2022-03-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_home', '0028_delete_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unconfirmedpasswordreset',
            name='email',
            field=models.EmailField(blank=True, max_length=320),
        ),
        migrations.AlterField(
            model_name='unconfirmeduser',
            name='email',
            field=models.EmailField(blank=True, max_length=320),
        ),
    ]
