# Generated by Django 3.2.10 on 2022-03-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_home', '0029_auto_20220312_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('file', models.FileField(blank=True, upload_to='files/')),
            ],
        ),
    ]
